BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Public] ADD [userId] INT;

-- AddForeignKey
ALTER TABLE [dbo].[Public] ADD CONSTRAINT [Public_userId_fkey] FOREIGN KEY ([userId]) REFERENCES [dbo].[User]([id]) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
